# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\x12\x07weather\"\x14\n\x04\x43ity\x12\x0c\n\x04name\x18\x01 \x01(\t\"2\n\x0bTemperature\x12\x12\n\nfahrenheit\x18\x01 \x01(\x02\x12\x0f\n\x07\x63\x65lcius\x18\x02 \x01(\x02\"!\n\x0bRelHumidity\x12\x12\n\npercentage\x18\x01 \x01(\x02\"a\n\x08\x44\x65tailed\x12)\n\x0btemperature\x18\x01 \x01(\x0b\x32\x14.weather.Temperature\x12*\n\x0crel_humidity\x18\x02 \x01(\x0b\x32\x14.weather.RelHumidity2\xb2\x01\n\x0eWeatherService\x12\x37\n\x0eGetTemperature\x12\r.weather.City\x1a\x14.weather.Temperature\"\x00\x12\x34\n\x0bGetHumidity\x12\r.weather.City\x1a\x14.weather.RelHumidity\"\x00\x12\x31\n\x0bGetDetailed\x12\r.weather.City\x1a\x11.weather.Detailed\"\x00\x62\x06proto3')



_CITY = DESCRIPTOR.message_types_by_name['City']
_TEMPERATURE = DESCRIPTOR.message_types_by_name['Temperature']
_RELHUMIDITY = DESCRIPTOR.message_types_by_name['RelHumidity']
_DETAILED = DESCRIPTOR.message_types_by_name['Detailed']
City = _reflection.GeneratedProtocolMessageType('City', (_message.Message,), {
  'DESCRIPTOR' : _CITY,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:weather.City)
  })
_sym_db.RegisterMessage(City)

Temperature = _reflection.GeneratedProtocolMessageType('Temperature', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATURE,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:weather.Temperature)
  })
_sym_db.RegisterMessage(Temperature)

RelHumidity = _reflection.GeneratedProtocolMessageType('RelHumidity', (_message.Message,), {
  'DESCRIPTOR' : _RELHUMIDITY,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:weather.RelHumidity)
  })
_sym_db.RegisterMessage(RelHumidity)

Detailed = _reflection.GeneratedProtocolMessageType('Detailed', (_message.Message,), {
  'DESCRIPTOR' : _DETAILED,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:weather.Detailed)
  })
_sym_db.RegisterMessage(Detailed)

_WEATHERSERVICE = DESCRIPTOR.services_by_name['WeatherService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CITY._serialized_start=26
  _CITY._serialized_end=46
  _TEMPERATURE._serialized_start=48
  _TEMPERATURE._serialized_end=98
  _RELHUMIDITY._serialized_start=100
  _RELHUMIDITY._serialized_end=133
  _DETAILED._serialized_start=135
  _DETAILED._serialized_end=232
  _WEATHERSERVICE._serialized_start=235
  _WEATHERSERVICE._serialized_end=413
# @@protoc_insertion_point(module_scope)
